### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by evoactivity** [LestaD/atom-gitlab#2]
I was pretty excited to see I'd be able to make merge requests with this but the only thing I get is a sidebar which does nothing? Does any of this work yet, or are you still actively developing it?

Looking through the code it looks like nothing is really implemented yet. That's a shame :( Probably shouldn't be published in atom at the moment since none of the features are implemented yet.

**Comment by sergeysova** [comment]
@evoactivity now i don't have a time to develop it.
does you want to be a contributor?

**Comment by mikaoelitiana** [comment]
@LestaD I am interested to contribute developping this plugin.

**Comment by sergeysova** [comment]
@mikaoelitiana you are contributor now

**Comment by mikaoelitiana** [comment]
@LestaD great, thanks, let me check the plugin code and status.
