### ISSUE TITLE
Windows Atom

### ISSUE THREAD

**Issue by flix444** [LestaD/atom-gitlab#7]
Hello, 
I use the Windows Atom Editor and install ur plugin but if i "click" clone nothing happen. 

I enter the Private Token and the Adresse of gitlab. 
Gitlab Version: 8.17.4

**Comment by hollandkyle** [comment]
Recurring issue on Windows Atom Editor, GitLab Enterprise Edition 9.4.0-rc2-ee

Expected: clone a project
Result: nothing
Settings: Private Token is correct, address is default https://gitlab.com
