### ISSUE TITLE
Fork GitHub

### ISSUE THREAD

**Issue by deckar01** [LestaD/atom-gitlab#8]
Development on this project seems to have stalled out. It might be more productive to fork [atom/github](https://github.com/atom/github).

Most of the features are generic git workflow tools, so they aren't specific to GitHub. It should be possible to wire up the "View Pull Request" feature up to the GitLab API and have a functional package.

**Comment by sergeysova** [comment]
@deckar01 I switched to VSCode, and now plugin is not develop

**Comment by deckar01** [comment]
No worries @LestaD. I am planning to start a fork this weekend.

**Comment by sergeysova** [comment]
@deckar01 when create repo, notify me, please!

**Comment by deckar01** [comment]
@LestaD I forked and made some basic changes, but decided to wait for now. I'm not sure I want to maintain a react app. Their code base was not fun. Maybe I just don't like react. :man_shrugging:
